From node:20.12.0-apline3.19

WORKDIR /usr/scr/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps

COPY packages ./packages

RUN npm install

RUN npm generate-db

RUN npm run build

CMD ["npm" , "run" , "start-user-app"] 
